sbatch submit_d_0.sh
sbatch submit_d_1.sh
sbatch submit_d_2.sh
sbatch submit_d_3.sh
sbatch submit_d_4.sh
sbatch submit_d_5.sh
sbatch submit_d_6.sh
sbatch submit_d_7.sh
sbatch submit_d_8.sh
sbatch submit_d_9.sh
sbatch submit_d_10.sh
sbatch submit_d_11.sh
sbatch submit_d_12.sh
sbatch submit_d_13.sh
sbatch submit_d_14.sh
sbatch submit_d_15.sh
sbatch submit_d_16.sh
sbatch submit_d_17.sh
sbatch submit_d_18.sh
sbatch submit_d_19.sh
sbatch submit_d_20.sh
sbatch submit_d_21.sh
sbatch submit_d_22.sh
sbatch submit_d_23.sh
sbatch submit_d_24.sh
sbatch submit_d_25.sh
sbatch submit_d_26.sh
sbatch submit_d_27.sh
sbatch submit_d_28.sh
sbatch submit_d_29.sh
sbatch submit_d_30.sh
sbatch submit_d_31.sh
sbatch submit_d_32.sh
sbatch submit_d_33.sh
sbatch submit_d_34.sh
sbatch submit_d_35.sh
sbatch submit_d_36.sh
sbatch submit_d_37.sh
sbatch submit_d_38.sh
sbatch submit_d_39.sh
sbatch submit_d_40.sh
sbatch submit_d_41.sh
sbatch submit_d_42.sh
sbatch submit_d_43.sh
sbatch submit_d_44.sh
sbatch submit_d_45.sh
sbatch submit_d_46.sh
sbatch submit_d_47.sh
sbatch submit_d_48.sh
sbatch submit_d_49.sh
sbatch submit_d_50.sh
sbatch submit_d_51.sh
sbatch submit_d_52.sh
sbatch submit_d_53.sh
sbatch submit_d_54.sh
sbatch submit_d_55.sh
sbatch submit_d_56.sh
sbatch submit_d_57.sh
sbatch submit_d_58.sh
sbatch submit_d_59.sh
sbatch submit_d_60.sh
sbatch submit_d_61.sh
sbatch submit_d_62.sh
sbatch submit_d_63.sh
sbatch submit_d_64.sh
sbatch submit_d_65.sh
sbatch submit_d_66.sh
sbatch submit_d_67.sh
sbatch submit_d_68.sh
sbatch submit_d_69.sh
sbatch submit_d_70.sh
sbatch submit_d_71.sh
sbatch submit_d_72.sh
sbatch submit_d_73.sh
sbatch submit_d_74.sh
sbatch submit_d_75.sh
sbatch submit_d_76.sh
sbatch submit_d_77.sh
sbatch submit_d_78.sh
sbatch submit_d_79.sh
sbatch submit_d_80.sh
sbatch submit_d_81.sh
sbatch submit_d_82.sh
sbatch submit_d_83.sh
sbatch submit_d_84.sh
sbatch submit_d_85.sh
sbatch submit_d_86.sh
sbatch submit_d_87.sh
sbatch submit_d_88.sh
sbatch submit_d_89.sh
sbatch submit_d_90.sh
sbatch submit_d_91.sh
sbatch submit_d_92.sh
sbatch submit_d_93.sh
sbatch submit_d_94.sh
sbatch submit_d_95.sh
sbatch submit_d_96.sh
sbatch submit_d_97.sh
sbatch submit_d_98.sh
sbatch submit_d_99.sh
