sbatch submit_0.sh
sbatch submit_1.sh
sbatch submit_2.sh
sbatch submit_3.sh
sbatch submit_4.sh
sbatch submit_5.sh
sbatch submit_6.sh
sbatch submit_7.sh
sbatch submit_8.sh
sbatch submit_9.sh
sbatch submit_10.sh
sbatch submit_11.sh
sbatch submit_12.sh
sbatch submit_13.sh
sbatch submit_14.sh
sbatch submit_15.sh
sbatch submit_16.sh
sbatch submit_17.sh
sbatch submit_18.sh
sbatch submit_19.sh
sbatch submit_20.sh
sbatch submit_21.sh
sbatch submit_22.sh
sbatch submit_23.sh
sbatch submit_24.sh
sbatch submit_25.sh
sbatch submit_26.sh
sbatch submit_27.sh
sbatch submit_28.sh
sbatch submit_29.sh
sbatch submit_30.sh
sbatch submit_31.sh
sbatch submit_32.sh
sbatch submit_33.sh
sbatch submit_34.sh
sbatch submit_35.sh
sbatch submit_36.sh
sbatch submit_37.sh
sbatch submit_38.sh
sbatch submit_39.sh
sbatch submit_40.sh
sbatch submit_41.sh
sbatch submit_42.sh
sbatch submit_43.sh
sbatch submit_44.sh
sbatch submit_45.sh
sbatch submit_46.sh
sbatch submit_47.sh
sbatch submit_48.sh
sbatch submit_49.sh
