sbatch submit_run_0.sh
sbatch submit_run_1.sh
sbatch submit_run_2.sh
sbatch submit_run_3.sh
sbatch submit_run_4.sh
sbatch submit_run_5.sh
sbatch submit_run_6.sh
sbatch submit_run_7.sh
sbatch submit_run_8.sh
sbatch submit_run_9.sh
sbatch submit_run_10.sh
sbatch submit_run_11.sh
sbatch submit_run_12.sh
sbatch submit_run_13.sh
sbatch submit_run_14.sh
sbatch submit_run_15.sh
sbatch submit_run_16.sh
sbatch submit_run_17.sh
sbatch submit_run_18.sh
sbatch submit_run_19.sh
sbatch submit_run_20.sh
sbatch submit_run_21.sh
sbatch submit_run_22.sh
sbatch submit_run_23.sh
sbatch submit_run_24.sh
sbatch submit_run_25.sh
sbatch submit_run_26.sh
sbatch submit_run_27.sh
sbatch submit_run_28.sh
sbatch submit_run_29.sh
sbatch submit_run_30.sh
sbatch submit_run_31.sh
sbatch submit_run_32.sh
sbatch submit_run_33.sh
sbatch submit_run_34.sh
sbatch submit_run_35.sh
sbatch submit_run_36.sh
sbatch submit_run_37.sh
sbatch submit_run_38.sh
sbatch submit_run_39.sh
sbatch submit_run_40.sh
sbatch submit_run_41.sh
sbatch submit_run_42.sh
sbatch submit_run_43.sh
sbatch submit_run_44.sh
sbatch submit_run_45.sh
sbatch submit_run_46.sh
sbatch submit_run_47.sh
sbatch submit_run_48.sh
sbatch submit_run_49.sh
sbatch submit_run_50.sh
sbatch submit_run_51.sh
sbatch submit_run_52.sh
sbatch submit_run_53.sh
sbatch submit_run_54.sh
sbatch submit_run_55.sh
sbatch submit_run_56.sh
sbatch submit_run_57.sh
sbatch submit_run_58.sh
sbatch submit_run_59.sh
sbatch submit_run_60.sh
sbatch submit_run_61.sh
sbatch submit_run_62.sh
sbatch submit_run_63.sh
sbatch submit_run_64.sh
sbatch submit_run_65.sh
sbatch submit_run_66.sh
sbatch submit_run_67.sh
sbatch submit_run_68.sh
sbatch submit_run_69.sh
sbatch submit_run_70.sh
sbatch submit_run_71.sh
sbatch submit_run_72.sh
sbatch submit_run_73.sh
sbatch submit_run_74.sh
sbatch submit_run_75.sh
sbatch submit_run_76.sh
sbatch submit_run_77.sh
sbatch submit_run_78.sh
sbatch submit_run_79.sh
sbatch submit_run_80.sh
sbatch submit_run_81.sh
sbatch submit_run_82.sh
sbatch submit_run_83.sh
sbatch submit_run_84.sh
sbatch submit_run_85.sh
sbatch submit_run_86.sh
sbatch submit_run_87.sh
sbatch submit_run_88.sh
sbatch submit_run_89.sh
sbatch submit_run_90.sh
sbatch submit_run_91.sh
sbatch submit_run_92.sh
sbatch submit_run_93.sh
sbatch submit_run_94.sh
sbatch submit_run_95.sh
sbatch submit_run_96.sh
sbatch submit_run_97.sh
sbatch submit_run_98.sh
sbatch submit_run_99.sh
sbatch submit_run_100.sh
sbatch submit_run_101.sh
sbatch submit_run_102.sh
sbatch submit_run_103.sh
sbatch submit_run_104.sh
sbatch submit_run_105.sh
sbatch submit_run_106.sh
sbatch submit_run_107.sh
sbatch submit_run_108.sh
sbatch submit_run_109.sh
sbatch submit_run_110.sh
sbatch submit_run_111.sh
sbatch submit_run_112.sh
sbatch submit_run_113.sh
sbatch submit_run_114.sh
sbatch submit_run_115.sh
sbatch submit_run_116.sh
sbatch submit_run_117.sh
sbatch submit_run_118.sh
sbatch submit_run_119.sh
sbatch submit_run_120.sh
sbatch submit_run_121.sh
sbatch submit_run_122.sh
sbatch submit_run_123.sh
sbatch submit_run_124.sh
sbatch submit_run_125.sh
sbatch submit_run_126.sh
sbatch submit_run_127.sh
sbatch submit_run_128.sh
sbatch submit_run_129.sh
sbatch submit_run_130.sh
sbatch submit_run_131.sh
sbatch submit_run_132.sh
sbatch submit_run_133.sh
sbatch submit_run_134.sh
