sbatch submit_g_0.sh
sbatch submit_g_1.sh
sbatch submit_g_2.sh
sbatch submit_g_3.sh
sbatch submit_g_4.sh
sbatch submit_g_5.sh
sbatch submit_g_6.sh
sbatch submit_g_7.sh
sbatch submit_g_8.sh
sbatch submit_g_9.sh
sbatch submit_g_10.sh
sbatch submit_g_11.sh
sbatch submit_g_12.sh
sbatch submit_g_13.sh
sbatch submit_g_14.sh
sbatch submit_g_15.sh
sbatch submit_g_16.sh
sbatch submit_g_17.sh
sbatch submit_g_18.sh
sbatch submit_g_19.sh
sbatch submit_g_20.sh
sbatch submit_g_21.sh
sbatch submit_g_22.sh
sbatch submit_g_23.sh
sbatch submit_g_24.sh
sbatch submit_g_25.sh
sbatch submit_g_26.sh
sbatch submit_g_27.sh
sbatch submit_g_28.sh
sbatch submit_g_29.sh
sbatch submit_g_30.sh
sbatch submit_g_31.sh
sbatch submit_g_32.sh
sbatch submit_g_33.sh
sbatch submit_g_34.sh
sbatch submit_g_35.sh
sbatch submit_g_36.sh
sbatch submit_g_37.sh
sbatch submit_g_38.sh
sbatch submit_g_39.sh
sbatch submit_g_40.sh
sbatch submit_g_41.sh
sbatch submit_g_42.sh
sbatch submit_g_43.sh
sbatch submit_g_44.sh
sbatch submit_g_45.sh
sbatch submit_g_46.sh
sbatch submit_g_47.sh
sbatch submit_g_48.sh
sbatch submit_g_49.sh
sbatch submit_g_50.sh
sbatch submit_g_51.sh
sbatch submit_g_52.sh
sbatch submit_g_53.sh
sbatch submit_g_54.sh
sbatch submit_g_55.sh
sbatch submit_g_56.sh
sbatch submit_g_57.sh
sbatch submit_g_58.sh
sbatch submit_g_59.sh
sbatch submit_g_60.sh
sbatch submit_g_61.sh
sbatch submit_g_62.sh
sbatch submit_g_63.sh
sbatch submit_g_64.sh
sbatch submit_g_65.sh
sbatch submit_g_66.sh
sbatch submit_g_67.sh
sbatch submit_g_68.sh
sbatch submit_g_69.sh
sbatch submit_g_70.sh
sbatch submit_g_71.sh
sbatch submit_g_72.sh
sbatch submit_g_73.sh
sbatch submit_g_74.sh
sbatch submit_g_75.sh
sbatch submit_g_76.sh
sbatch submit_g_77.sh
sbatch submit_g_78.sh
sbatch submit_g_79.sh
sbatch submit_g_80.sh
sbatch submit_g_81.sh
sbatch submit_g_82.sh
sbatch submit_g_83.sh
sbatch submit_g_84.sh
sbatch submit_g_85.sh
sbatch submit_g_86.sh
sbatch submit_g_87.sh
sbatch submit_g_88.sh
sbatch submit_g_89.sh
sbatch submit_g_90.sh
sbatch submit_g_91.sh
sbatch submit_g_92.sh
sbatch submit_g_93.sh
sbatch submit_g_94.sh
sbatch submit_g_95.sh
sbatch submit_g_96.sh
sbatch submit_g_97.sh
sbatch submit_g_98.sh
sbatch submit_g_99.sh
